spring.application.name=sonede-auth
server.port=8080

spring.data.mongodb.uri=mongodb://localhost:27017/sonede_smart_platform

spring.docker.compose.enabled=false

# 64-byte base64 encoded secret:
jwt.secret=v8R9N3pP6mXb/L+G4QcW2sA5hY7zJkV0nU1dF3tE8vR9N3pP6mXb/L+G4QcW2sA5hY7zJkV0nU1dF3tE8=
jwt.access-token-expiration=86400000
jwt.refresh-token-expiration=604800000

app.cors.allowed-origins=http://localhost:3000,http://localhost:63131

spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=mecherguia967@gmail.com
spring.mail.password=ehst oond qlwg lhhz
spring.mail.properties.from=mecherguia967@gmail.com
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.properties.mail.debug=true
